### ISSUE TITLE
[Discussion] Which technology to use for automation task

### ISSUE THREAD

**Issue by vn-patriot** [findgeek/geekjob#3]
So far, we already have the GitHub and proper telegram channel. 
Next thing is we need to post the job (which got approval) from GitHub to Telegram sequently. 

I am thinking about 2 options : [Zapier](zapier.com) vs [IFTTT](ifttt.com)

There is minimal comparing [here ](https://www.process.st/zapier-vs-ifttt/)

So ideally, it should be automated as much as possible. 

Remember, we will have 2 flows 

**From GitHub to Telegram & Google Form to Telegram.**

**Comment by onimsha** [comment]
should we write a small bot program and self-hosted it ? I'm not very familiar with the bot ecosystem so not sure which tools are better.

**Comment by ngoduykhanh** [comment]
> From GitHub to Telegram & Google Form to Telegram.

Are they 2 independent sources? Shouldn't we push data from Google form to Github also, and then everything from Github will be pushed to Telegram.

**Comment by vn-patriot** [comment]
Centralisation like @ngoduykhanh  said is decent !

I think before to write the small bot program I would give it a try @onimsha :D. My most concern is about cost optimisation. 
So let's say if we have a huge load of the jobs posting then ok it should not be a problem to invest $. So far both 2 solutions above offered free .. (has some limitations 100 works / month)

**Comment by ngoduykhanh** [comment]
Github Action has some bot for Telegram notification. I think we can give a try. Eg. https://github.com/marketplace/actions/telegram-notify

**Comment by onimsha** [comment]
yeah that's will do for the posting basic. Just checked this https://probot.github.io/docs/ , looks good and we can do more housekeeping stuff, like labelling, commenting etc... But it could be later, though.

**Comment by onimsha** [comment]
@ngoduykhanh  looks at the action i think we also should decide WHAT to post to Telegram. Should we post the whole markdown contents of the PR or just part of it, or just the link to the file on the Github repo ?

There are limitations if we use the https://github.com/marketplace/actions/telegram-notify so we either use something compatible with it or create our own action.

**Comment by vn-patriot** [comment]
In my opinion: i would like to post the whole job description instead of the link to the GH file. 
Actually in the future, i want to get rid of those own links, so people when access to the telegram job channel will able to read the JD, if they either want to apply / ask, it will show like that. Then just click

![image](https://user-images.githubusercontent.com/36286578/95945416-ba0f3800-0dea-11eb-85bd-564d9d43d519.png)

**Comment by onimsha** [comment]
As per our call last night, we will have switch from PR-based to Issue-based for job posting, and the github actions will post to Telegram with the Issue's contents, once it's being approved. It may not the final decision yet but we'll see.
