### ISSUE TITLE
[Discussion] Changing the approach on job posting

### ISSUE THREAD

**Issue by onimsha** [findgeek/geekjob#6]
During our last video call, @ngoduykhanh pointed out that using a PR-based system for job posting is not user-friendly, especially for recruiters. Even with people know how to use Github, the cost of creating a PR just for posting job is quite high, since they have to deal with fork, commit, push etc... Although we want to do something geeky for this project, it actually discourage people to coming and engaging with us. 

So i'm putting a new proposal that we will switch back to Issue-based system, which using following concepts:

1. Uses Github Issues for job posting. An Issue template will be provided for open a new job posting.  
2. Uses label for classifying / automation.  
3. Uses Github Actions for posting job to Telegram once it's being approved by maintainers.  

TO-DO:

- [x] Change job posting rules to describe how to use Github Issues rather than PR (@onimsha )

- [x] Create the specification for the Telegram posting action (@onimsha )

- [x] Develop a custom action to post to Telegram according to the specs (@ngoduykhanh )

**Comment by ngoduykhanh** [comment]
As I understand the basic workflow would like this:
- User ---> _Open Issue ---> Test / Assign labels (Auto) ---> Approval (Manual) ---> PR --- Merge (Auto) ---> Static pages_.
- User ---> Form ---> _Open Issue ---> Test / Assign labels (Auto) ---> Approval (Manual) ---> PR --- Merge (Auto) ---> Static pages_.

Github Actions supports most of the events we need. However, for each action, it will create a build that runs on a container or machine. This is ok for "New Issue" events but if we want to integrate further, with labeling or commenting, for example, it would take time. So for the flexibility, I'll create a small API to handle Github webhook call and do other actions. It would help if we want to have our own form also.

**Comment by ngoduykhanh** [comment]
See https://github.com/findgeek/artemis

**Comment by onimsha** [comment]
noooooo, it should be `mirana` https://dota2.gamepedia.com/Mirana

**Comment by ngoduykhanh** [comment]
@onimsha I am working on a PR for Artemis [here](https://github.com/findgeek/artemis/pull/2/files)
In order to get the job (issue) posted to repo's `main` branch. The `Issue` must:
- Have a proper content (TODO: defining the Issue template for `geekjob` repo)
- Have proper labeling: `approved` label for the approval and a [job category label](https://github.com/findgeek/artemis/blob/7c93ca51236e941460b6ffdf85e9627e98d49b73/src/app/const.py#L10-L16).

Open to discuss:
- Should we lock/close the issue after posting it to `main`?
- Are we able to let users use some specific labels? E.g. only job category labels, not `approved` label.

**Comment by onimsha** [comment]
For the sake of timeline, i think at this moment we won't implement the feature to convert Issue to PR yet. This feature will be considered in the future . @ngoduykhanh 

So the workflow should be this User ---> Open Issue ---> Test / Assign labels (Auto) ---> Approval (Manual) ---> Post to Telegram

**Comment by onimsha** [comment]
@ngoduykhanh  i made a proposal for issue lifecycle management here https://github.com/findgeek/artemis/issues/3 

> Should we lock/close the issue after posting it to main?  

I think we should only lock. We only close issue after the expiration date. 

> Are we able to let users use some specific labels? E.g. only job category labels, not approved label.  

Yes, i think it's ok.
